# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zT4eFKWNKxAurfADA3NdoQNgQXMb9ZLr
"""

!pip install pyspark

from pyspark.sql import SparkSession
spark=SparkSession.builder\
        .appName("Ridesharing Analysis")\
        .getOrCreate()

print("Spark Session Created!")
print(spark.version)

from pyspark.sql.types import StructType,StructField,StringType,DoubleType

schema=StructType([
    StructField("trip_id",StringType(),True),
    StructField("driver_id",StringType(),True),
    StructField("city",StringType(),True),
    StructField("distance_km",DoubleType(),True),
    StructField("fare_usd",DoubleType(),True),
    StructField("status",StringType(),True)
])

data = [
    ("T001", "D001", "New York", 5.2,  12.50, "completed"),
    ("T002", "D002", "Chicago",  3.1,  8.00,  "cancelled"),
    ("T003", "D001", "New York", 8.7,  21.00, "completed"),
    ("T004", "D003", "Chicago",  2.5,  6.50,  "completed"),
    ("T005", "D002", "New York", 6.3,  15.00, "cancelled"),
    ("T006", "D003", "New York", 4.1,  10.00, "completed"),
    ("T007", "D001", "Chicago",  9.2,  22.50, "completed"),
    ("T008", "D002", "Chicago",  1.8,  5.00,  "cancelled")
]

df = spark.createDataFrame(data, schema)
df.show()

completed_df=df.filter(df["status"] == "completed")
completed_df.show()

from pyspark.sql.functions import sum,avg

result_df= completed_df.groupBy("city").agg(
    sum("fare_usd").alias("total_fare"),
    avg("distance_km").alias("avg_distance")
)
result_df.show()

final_df=result_df.orderBy("total_fare",ascending=False)
final_df.show()